engines = {
    "ab" : { "name": "askubuntu", "link": "http://askubuntu.com/search?q="},
    "bi" : { "name": "bing", "link": "https://www.bing.com/search?q="},
    "dd" : { "name": "duckduckgo", "link": "https://www.duckduckgo.com/?q="},
    "gi" : { "name": "github", "link": "https://github.com/search?q="},
    "go" : { "name": "google", "link": "https://www.google.com/search?q="},
    "oh" : { "name": "openhub", "link": "https://www.openhub.net/p?ref=homepage&query="},
    "pb" : { "name": "piratebay", "link": "https://thepiratebay.org/search/"},
    "rt" : { "name": "rottentomatoes", "link": "https://www.rottentomatoes.com/search/?search="},
    "sc" : { "name": "searchcode", "link": "https://searchcode.com/?q="},
    "so" : { "name": "stackoverflow", "link": "http://stackoverflow.com/search?q="},
    "su" : { "name": "superuser", "link": "http://superuser.com/search?q="},
    "sy" : { "name": "symbolhound", "link": "http://symbolhound.com/?q="},
    "vi" : { "name": "vimawesome", "link": "http://vimawesome.com/?q="},
    "ya" : { "name": "yahoo", "link": "https://search.yahoo.com/search?p="},
    "ya" : { "name": "yandex", "link": "https://yandex.ru/yandsearch?text="},
    "yt" : { "name": "youtube", "link": "https://www.youtube.com/results?search_query="},
}
