
laravel_data = {
    "Release Notes": "https://laravel.com/docs/{version}/releases",
    "Upgrade Guide": "https://laravel.com/docs/{version}/upgrade",
    "Contribution Guide":"https://laravel.com/docs/{version}/contributions",
    "Installation":"https://laravel.com/docs/{version}/installation",
    "Configuration":"https://laravel.com/docs/{version}/configuration",
    "Directory Structure":"https://laravel.com/docs/{version}/structure",
    "Frontend":"https://laravel.com/docs/{version}/frontend",
    "Starter Kits":"https://laravel.com/docs/{version}/starter-kits",
    "Deployment":"https://laravel.com/docs/{version}/deployment",
    "Request Lifecycle":"https://laravel.com/docs/{version}/lifecycle",
    "Service Container":"https://laravel.com/docs/{version}/container",
    "Service Providers":"https://laravel.com/docs/{version}/providers",
    "Facades":"https://laravel.com/docs/{version}/facades",
    "Routing":"https://laravel.com/docs/{version}/routing",
    "Middleware":"https://laravel.com/docs/{version}/middleware",
    "CSRF Protection":"https://laravel.com/docs/{version}/csrf",
    "Controllers":"https://laravel.com/docs/{version}/controllers",
    "Requests":"https://laravel.com/docs/{version}/requests",
    "Responses":"https://laravel.com/docs/{version}/responses",
    "Views":"https://laravel.com/docs/{version}/views",
    "Blade Templates":"https://laravel.com/docs/{version}/blade",
    "Asset Bundling":"https://laravel.com/docs/{version}/vite",
    "URL Generation":"https://laravel.com/docs/{version}/urls",
    "Session":"https://laravel.com/docs/{version}/session",
    "Validation":"https://laravel.com/docs/{version}/validation",
    "Error Handling":"https://laravel.com/docs/{version}/errors",
    "Logging":"https://laravel.com/docs/{version}/logging",
    "Artisan Console":"https://laravel.com/docs/{version}/artisan",
    "Broadcasting":"https://laravel.com/docs/{version}/broadcasting",
    "Cache":"https://laravel.com/docs/{version}/cache",
    "Collections":"https://laravel.com/docs/{version}/collections",
    "Contracts":"https://laravel.com/docs/{version}/contracts",
    "Events":"https://laravel.com/docs/{version}/events",
    "File Storage":"https://laravel.com/docs/{version}/filesystem",
    "Helpers":"https://laravel.com/docs/{version}/helpers",
    "HTTP Client":"https://laravel.com/docs/{version}/http-client",
    "Localization":"https://laravel.com/docs/{version}/localization",
    "Mail":"https://laravel.com/docs/{version}/mail",
    "Notifications":"https://laravel.com/docs/{version}/notifications",
    "Package Development":"https://laravel.com/docs/{version}/packages",
    "Processes":"https://laravel.com/docs/{version}/processes",
    "Queues":"https://laravel.com/docs/{version}/queues",
    "Rate Limiting":"https://laravel.com/docs/{version}/rate-limiting",
    "Strings":"https://laravel.com/docs/{version}/strings",
    "Task Scheduling":"https://laravel.com/docs/{version}/scheduling",
    "Authentication":"https://laravel.com/docs/{version}/authentication",
    "Authorization":"https://laravel.com/docs/{version}/authorization",
    "Email Verification":"https://laravel.com/docs/{version}/verification",
    "Encryption":"https://laravel.com/docs/{version}/encryption",
    "Hashing":"https://laravel.com/docs/{version}/hashing",
    "Password Reset":"https://laravel.com/docs/{version}/passwords",
    "Getting Started":"https://laravel.com/docs/{version}/database",
    "Query Builder":"https://laravel.com/docs/{version}/queries",
    "Pagination":"https://laravel.com/docs/{version}/pagination",
    "Migrations":"https://laravel.com/docs/{version}/migrations",
    "Seeding":"https://laravel.com/docs/{version}/seeding",
    "Redis":"https://laravel.com/docs/{version}/redis",
    "Getting Started":"https://laravel.com/docs/{version}/eloquent",
    "Relationships":"https://laravel.com/docs/{version}/eloquent-relationships",
    "Collections":"https://laravel.com/docs/{version}/eloquent-collections",
    "Mutators / Casts":"https://laravel.com/docs/{version}/eloquent-mutators",
    "API Resources":"https://laravel.com/docs/{version}/eloquent-resources",
    "Serialization":"https://laravel.com/docs/{version}/eloquent-serialization",
    "Factories":"https://laravel.com/docs/{version}/eloquent-factories",
    "Getting Started":"https://laravel.com/docs/{version}/testing",
    "HTTP Tests":"https://laravel.com/docs/{version}/http-tests",
    "Console Tests":"https://laravel.com/docs/{version}/console-tests",
    "Browser Tests":"https://laravel.com/docs/{version}/dusk",
    "Database":"https://laravel.com/docs/{version}/database-testing",
    "Mocking":"https://laravel.com/docs/{version}/mocking",
    "Breeze":"https://laravel.com/docs/{version}/starter-kits#laravel-breeze",
    "Cashier (Stripe)":"https://laravel.com/docs/{version}/billing",
    "Cashier (Paddle)":"https://laravel.com/docs/{version}/cashier-paddle",
    "Dusk":"https://laravel.com/docs/{version}/dusk",
    "Envoy":"https://laravel.com/docs/{version}/envoy",
    "Fortify":"https://laravel.com/docs/{version}/fortify",
    "Folio":"https://laravel.com/docs/{version}/folio",
    "Homestead":"https://laravel.com/docs/{version}/homestead",
    "Horizon":"https://laravel.com/docs/{version}/horizon",
    "Jetstream": "https://jetstream.laravel.com",
    "Mix":"https://laravel.com/docs/{version}/mix",
    "Octane":"https://laravel.com/docs/{version}/octane",
    "Passport":"https://laravel.com/docs/{version}/passport",
    "Pennant":"https://laravel.com/docs/{version}/pennant",
    "Pint":"https://laravel.com/docs/{version}/pint",
    "Precognition":"https://laravel.com/docs/{version}/precognition",
    "Prompts":"https://laravel.com/docs/{version}/prompts",
    "Pulse":"https://laravel.com/docs/{version}/pulse",
    "Sail":"https://laravel.com/docs/{version}/sail",
    "Sanctum":"https://laravel.com/docs/{version}/sanctum",
    "Scout":"https://laravel.com/docs/{version}/scout",
    "Socialite":"https://laravel.com/docs/{version}/socialite",
    "Telescope":"https://laravel.com/docs/{version}/telescope",
    "Valet":"https://laravel.com/docs/{version}/valet",
    "API Documentation":"/api/{version}",
}
